language: php
sudo: required
dist: trusty
php:
- 5.6
env:
  global:
  - PULSESTORM_MAGE2_FAKE_URL=http://magento-2-travis.dev
  - PULSESTORM_MAGE2_ADMIN_EMAIL=robert.hoffner@example.com
  - PULSESTORM_MAGE2_ADMIN_FIRST_NAME=Robert
  - PULSESTORM_MAGE2_ADMIN_LAST_NAME=Hoffner
  - PULSESTORM_MAGE2_ADMIN_USERNAME=admin
  - PULSESTORM_MAGE2_ADMIN_PASSWORD=ih3artmagento
  - PULSESTORM_MAGE2_ADMIN_DBNAME=magento_2_travis
  - PULSESTORM_PESTLE_URL=http://pestle.pulsestorm.net
  - PULSESTORM_COMPOSER_REPOSITORY_TO_TEST=git@github.com:SummaSolutions/cart-magento2.git
  - PULSESTORM_COMPOSER_PACKAGE_TO_TEST=mercadopago/magento2-plugin
addons:
  hosts:
  - magento-2-travis.dev
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
before_script:
- composer selfupdate
- echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse"
  && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates
  multiverse"
- sudo apt-get update -qq
- sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5
  mysql-client-5.5 mysql-client-core-5.5
- sudo apt-get -y -qq autoremove;
- sudo apt-get -y -qq autoclean;
- sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6;
- mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE
  magento_2_travis;';
- sudo apt-get install -y -qq apache2 libapache2-mod-fastcgi
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default
  ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null ||
  true
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv
  version-name)/etc/php-fpm.conf
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- "~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm"
- sudo chmod 777 /home /home/travis /home/travis/build
- sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
- sudo service apache2 restart
- ls
- curl -LO "$PULSESTORM_PESTLE_URL/pestle.phar"
- sudo mv pestle.phar /usr/local/bin
- sudo chmod +x /usr/local/bin/pestle.phar
- cp -f .travis/composer.json composer.json
- composer global config http-basic.repo.magento.com f2618fa3a9f0fe7002b8c5edaea0ed22
  3db3f6c9b5cf1734e2dfa13979ef9d3a
- composer install --no-interaction
- mkdir tmp
- sudo chown -R :www-data .
- sudo find . -type d -exec chmod 770 {} \; && sudo find . -type f -exec chmod 660
  {} \; && sudo chmod u+x bin/magento
- bin/magento setup:install --backend-frontname=admin --db-host=localhost --db-name=magento_2_travis
  --db-user root --base-url=http://magento-2-travis.dev/ --use-secure-admin=0 --admin-user=admin
  --admin-password=MercadoPago2016 --admin-email=fcapua@summasolutions.net --admin-firstname=Facundo
  --admin-lastname=Capua --cleanup-database --use-sample-data
- wget -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
- unzip ngrok.zip
- "./ngrok http --log=stdout --log-level=debug -host-header=magento-2-travis.dev 80"
- cd app/code/MercadoPago/Core/Test
- cp behat.yml.dist behat.yml
- sed -e "s?%MAGENTO_URL%?http://magento-2-travis.dev/?g" --in-place behat.yml
- sed -e "s?%BROWSER_DRIVER%?firefox?g" --in-place behat.yml
- composer install --no-interaction
- sh -e /etc/init.d/xvfb start
- export DISPLAY=:99.0
- wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
- java -jar selenium-server-standalone-2.47.1.jar -log /tmp/selenium.log > /dev/null
  &
script:
- vendor/bin/behat --config behat.yml --tags @viewStandard --tags="~@skip"
- wget -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
- unzip ngrok.zip
- ngrok http -log=stdout -subdomain=magento-2-travis.dev 9000
deploy:
  provider: releases
  api_key:
    secure: ifyfY3fHQubZ+9FHQm5XcgFb+IspMt5tD87PFzKh99+P6X0nUcaHYoSKZ+ASMw0dESzXHEDi4i6oS1Xv8IspUPsyKCYdii41Oi/zHiGUNPnk96mey/Ucvr8tYKTYxlNQ5uA1GKGfxM3RGb7EHeD40PXQa3elSDJY5BLFvUSJquuHD+GC9ZQ1V9a3LbYHkZPiHAcg5S7cAm+h+EEqWuxeMv6KDA6Heyb5cyGkG5QEOU5QvNxvfSKSSXsQBdVBC1pXSF+xjNHKz+58b5rdFC3RWjVBIFzP8VtVI8RT1+J7l8bOHzT3BLEigTLbTHZc6WUyaDK0NWkj+rlV3ChtRTP9vckW4ew/McV1tXpkduonhO6xG9RDyVtBhareIAheHDSfDSVi8CtKSeozEHzX+zcUjftbfbrD8cQkb49qLGXQeY5JOb04EF6BT6UjpjXcghbx1bKVGSj5zmHSzX28Ml0warhd64E5VbxbBikkcqgjF+bQv/77tys/0MG8vOB1IVDA3FhW0VHMSp1q9Ag3Qxc2R56cBE1371tyTiq8LKMl1dZTvgyAj6ZzWFjsoVY2y2i8IJrm/Es8f747PGtilDXRDXTjEJE60gLzDArMYzA3LF0++//yfkmxB4UdAQBqivL0oslXBbXyc75QDEEdB+Bx0gZdNJaSkSygwr0NUcgBrto=
  file: screenshot.png
  on:
    repo: imasson/cart-magento2
    branch: develop_travis
