env:
    #global environmental variables control magento instal parameters
    #see also hosts in addons.
    global:
    - PULSESTORM_MAGE2_FAKE_URL=http://magento-2-travis.dev
    - PULSESTORM_MAGE2_ADMIN_EMAIL=robert.hoffner@example.com
    - PULSESTORM_MAGE2_ADMIN_FIRST_NAME=Robert    
    - PULSESTORM_MAGE2_ADMIN_LAST_NAME=Hoffner
    - PULSESTORM_MAGE2_ADMIN_USERNAME=admin            
    - PULSESTORM_MAGE2_ADMIN_PASSWORD=ih3artmagento            
    - PULSESTORM_MAGE2_ADMIN_DBNAME=magento_2_travis                
    - PULSESTORM_PESTLE_URL=http://pestle.pulsestorm.net  
    - PULSESTORM_COMPOSER_REPOSITORY_TO_TEST=git@github.com:SummaSolutions/cart-magento2.git
    - PULSESTORM_COMPOSER_PACKAGE_TO_TEST=mercadopago/magento2-plugin
addons:
  hosts:
    # should match PULSESTORM_MAGE2_FAKE_URL above
    - magento-2-travis.dev    
language: php
sudo: required
dist: trusty
php:
   - 5.6
before_script:
    # some useful debugging stuff for travis
    #- curl http://magento-2-travis.dev/index.php
    #- curl http://magento-2-travis.dev/  
    #- sudo find /var/log/apache2 -exec cat '{}' \;      
    #- sudo cat /etc/apache2/sites-available/000-default.conf
    #- sudo cat /etc/apache2/sites-enabled/000-default.conf    
    #- sudo apachectl -V
    #- sudo apache2ctl -V
    #- ls -lh $TRAVIS_BUILD_DIR
    #- sudo ls /etc/apache2/sites-available
    #- sudo ls /etc/apache2/sites-enabled
    #- pwd    
    #    
    # get latest composer 
    - composer selfupdate
    # disable xdebug for perf    
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini   
    # add multiverse support to get MySQL 5.6 update apt
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse" && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
    - sudo apt-get update -qq 
    # add mysql 5.6
    - sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
    - sudo apt-get -y -qq autoremove;
    - sudo apt-get -y -qq autoclean;
    - sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6;    
    - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_2_travis;';
    # add apache
    - sudo apt-get install -y -qq apache2 libapache2-mod-fastcgi
    #   enable php-fpm -- www.conf.default is PHP 7 only, so we dev/null any copy problems    
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true  
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    #   awful hack used during travis debugging that I swear I'm going to remove
    #   but then again you're reading this so I didn't remove it and **sigh**    
    - sudo chmod 777 /home /home/travis /home/travis/build            

    #   configure apache virtual hosts, assumes 000-default.conf is there
    - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    # restart apache
    - sudo service apache2 restart 

    # clone main magento github repository
    #- git clone https://github.com/magento/magento2
    - ls
    # download latest pestle phar and install
    - curl -LO "$PULSESTORM_PESTLE_URL/pestle.phar"
    - sudo mv pestle.phar /usr/local/bin
    - sudo chmod +x /usr/local/bin/pestle.phar
    # install Magento
    - cp -f .travis/composer.json composer.json
    - composer global config http-basic.repo.magento.com f2618fa3a9f0fe7002b8c5edaea0ed22 3db3f6c9b5cf1734e2dfa13979ef9d3a
    - composer install --no-interaction
    - mkdir tmp
    - sudo chown -R :www-data .
    - sudo find . -type d -exec chmod 770 {} \; && sudo find . -type f -exec chmod 660 {} \; && sudo chmod u+x bin/magento
    - bin/magento setup:install --backend-frontname=admin --db-host=localhost --db-name=magento_2_travis --db-user root --base-url=http://magento-2-travis.dev/ --use-secure-admin=0 --admin-user=admin --admin-password=MercadoPago2016 --admin-email=fcapua@summasolutions.net --admin-firstname=Facundo --admin-lastname=Capua --cleanup-database --use-sample-data
    - cd app/code/MercadoPago/Core/Test
    - curl http://magento-2-travis.dev/ > /tmp/pepe.log
    - sudo cat /tmp/pepe.log
    #- cp behat.yml.dist behat.yml
    #- sed -e "s?%MAGENTO_URL%?http://${MAGENTO_URL}/?g" --in-place behat.yml
    #- sed -e "s?%BROWSER_DRIVER%?firefox?g" --in-place behat.yml
    #- composer install --no-interaction
    #- "sh -e /etc/init.d/xvfb start"
    #- "export DISPLAY=:99.0"
    #- "wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar"
    #- "java -jar selenium-server-standalone-2.47.1.jar -log /tmp/selenium.log > /dev/null &"
script: test 'grep -Fx "magento-2-travis.dev" /tmp/output.txt'